spring.datasource.url=jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/shuttle_db?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=4Bos9C2srKVNsaB.root
spring.datasource.password=2WBpDoD567FHjqYB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.TiDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjVjYjRjNzYzYjljODRlZWE5NWU0M2YyY2Y3NWMwZDA1IiwiaCI6Im11cm11cjY0In0=

# Geoapify API Key
geoapify.api.key=5b203f6b8e664a33b2f195b69f16544c

server.port=8080